#!/usr/bin/env python3
"""Generate a weekly adoption + social-post draft from real evidence.

This is the deterministic half of the growth loop's "draft" step (Tier 1). It reads
the funnel tracker and the week's git history, then emits a Markdown draft — a digest
plus a claim-safe X post stub — for a human to review in the social queue.

It NEVER posts anything. Output is text. Publishing stays human-gated by design.
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import statistics
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

TRUTHY = {"yes", "y", "true", "1", "x", "done", "✅"}

# Paths whose commits this week count as "what shipped" worth talking about.
CATALOG_PATHS = ["pkg/ai/catalog.go"]
COMPAT_PATHS = ["docs/ueransim-compat.md", "docs/real-ran-compat.md"]


def truthy(value: str) -> bool:
    return value.strip().lower() in TRUTHY


def is_example(row: dict) -> bool:
    tester = (row.get("tester") or "").strip().lower()
    return tester == "" or tester.startswith("_ex_") or tester.startswith("ex ")


def load_rows(tracker: Path) -> list[dict]:
    if not tracker.exists():
        return []
    with tracker.open(newline="") as fh:
        return [r for r in csv.DictReader(fh) if not is_example(r)]


def median_seconds(rows: list[dict], col: str) -> float | None:
    vals = []
    for r in rows:
        raw = (r.get(col) or "").strip()
        try:
            vals.append(float(raw))
        except ValueError:
            continue
    return statistics.median(vals) if vals else None


def git_log_since(days: int, paths: list[str]) -> list[str]:
    try:
        out = subprocess.run(
            ["git", "log", f"--since={days} days ago", "--pretty=format:%h %s", "--", *paths],
            cwd=REPO, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    return [ln for ln in out.splitlines() if ln.strip()]


def fmt_seconds(value: float | None) -> str:
    return f"{value:.1f}s" if value is not None else "—"


def build_draft(rows: list[dict], days: int) -> str:
    counts = {
        c: sum(1 for r in rows if truthy(r.get(c, "")))
        for c in ("reached", "cloned", "first_connection", "first_diagnosis", "returned", "advocated")
    }
    nailed = sum(1 for r in rows if truthy(r.get("diagnosis_nailed_it", "")))
    ttfc = median_seconds(rows, "ttfc_s")
    ttrc = median_seconds(rows, "ttrc_s")
    catalog = git_log_since(days, CATALOG_PATHS)
    compat = git_log_since(days, COMPAT_PATHS)
    today = dt.date.today().isoformat()

    L: list[str] = []
    L.append(f"## 📣 Weekly adoption draft — {today}")
    L.append("")
    L.append(f"_Window: last {days} days. Generated by `make adoption-draft`. "
             "**Review and edit before posting — nothing here is published automatically.**_")
    L.append("")
    L.append("### Funnel snapshot")
    L.append("")
    L.append("| Stage | Count |")
    L.append("|---|---|")
    L.append(f"| Reached | {counts['reached']} |")
    L.append(f"| Cloned | {counts['cloned']} |")
    L.append(f"| First connection (TTFC) | {counts['first_connection']} · median {fmt_seconds(ttfc)} |")
    L.append(f"| First diagnosis (TTRC) | {counts['first_diagnosis']} · median {fmt_seconds(ttrc)} |")
    L.append(f"| Diagnosis nailed it | {nailed} |")
    L.append(f"| Returned | {counts['returned']} |")
    L.append(f"| Advocated | {counts['advocated']} |")
    L.append("")

    L.append("### What shipped this week (talkable)")
    L.append("")
    if catalog:
        L.append(f"- **{len(catalog)} diagnostic-catalog commit(s)** — new rules from real failures:")
        L += [f"  - `{c}`" for c in catalog]
    else:
        L.append("- No new catalog rules this week.")
    if compat:
        L.append(f"- **{len(compat)} compatibility-finding commit(s)**:")
        L += [f"  - `{c}`" for c in compat]
    else:
        L.append("- No new compatibility findings this week.")
    L.append("")

    L.append("### Draft X post (claim-safe — EDIT before posting)")
    L.append("")
    L.append("> ```")
    if counts["first_diagnosis"] > 0:
        L.append("> This week QCore explained a real attach failure to an outside tester —")
        L.append(f"> cause + fix on both sides, median {fmt_seconds(ttrc)} to root cause.")
    elif catalog:
        L.append("> QCore got smarter this week: every real failure a tester hits becomes a")
        L.append("> permanent diagnostic rule, so the next dev never debugs it from scratch.")
    else:
        L.append("> An open-source 4G/5G core that explains *why* your attach failed —")
        L.append("> cause + fix on both sides. Looking for honest cold runs.")
    L.append("> git clone https://github.com/umairsuperhero/qcore && cd qcore && make up-5g")
    L.append("> ```")
    L.append("")
    L.append("**Claim-safety check before you post** (see `docs/outreach-kit.md`):")
    L.append("- ✅ \"validated against the bundled UERANSIM Docker/Linux profile\"")
    L.append("- ❌ NOT \"3GPP certified\", \"works with every gNB/UE\", or \"production carrier core\"")
    L.append("- ❌ Don't say \"externally validated\" until a real external run actually exists")
    L.append("")
    L.append("### Operator action")
    L.append("- [ ] Pick the single highest-friction tester note → one fix / catalog rule / caveat.")
    L.append("- [ ] Edit the post above, then publish manually or via the `post-to-x` workflow.")
    return "\n".join(L) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tracker", default=str(REPO / "docs/adoption-tracker.csv"))
    ap.add_argument("--since-days", type=int, default=7)
    ap.add_argument("--output", default="", help="Write to file instead of stdout.")
    args = ap.parse_args()

    rows = load_rows(Path(args.tracker))
    draft = build_draft(rows, args.since_days)

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(draft)
    else:
        print(draft, end="")


if __name__ == "__main__":
    main()
