FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/upf ./cmd/upf

FROM alpine:latest
RUN apk --no-cache add ca-certificates iproute2 iptables
COPY --from=builder /bin/upf /bin/upf

ENTRYPOINT ["/bin/upf"]
