FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/smf ./cmd/smf

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /bin/smf /bin/smf

ENTRYPOINT ["/bin/smf"]
